version: '2'

services:
  
  nifi:
    image: apache/nifi:latest
    container_name: nifiDP2
    restart: always
    volumes:
      - ./nifi/:/home/nifi/
    ports:
      - '8090:8090'
    environment:
      - NIFI_WEB_HTTP_PORT=8090

networks:
  default:
    driver: bridge